- platform: modbus_controller
  modbus_controller_id: ${modbus_contr_id}
  # name: "${name} Config Switches Sensor"      # 
  id: CfgSwS
  address: 0x1114
  # address: 0x1100
  # offset: 0x0014
  register_type: holding
  value_type: U_WORD
  # skip_updates: 0
  # use_write_multiple: true
  # restore_value: true

    #    0x0118  280 UINT8   2   RW  Intelligent sleep time                              TIMSmartSleep       H
    #                UINT8       R   Data field enable control 0                         
- platform: modbus_controller
  modbus_controller_id: ${modbus_contr_id}
  # name: "${name} Intelligent sleep time"      # TIMSmartSleep
  id: TIMSmartSleepS
  address: 0x1118
  # address: 0x1100
  # offset: 0x0018
  register_type: holding
  value_type: U_WORD
  bitmask: 0xFF00

- platform: modbus_controller
  modbus_controller_id: ${modbus_contr_id}
  name: "${name} Intelligent sleep time control enable"      #
  id: TIMSmartSleepENS
  address: 0x1118
  # address: 0x1100
  # offset: 0x0018
  register_type: holding
  value_type: U_WORD
  bitmask: 0x00FF
