  #         0x0100  256 UINT32  4   R   RTC counter                                         RTCTicks                Starts counting from 2020-1-1
- platform: modbus_controller
  modbus_controller_id: ${modbus_contr_id}
  name: "${name} RTC counter"
  # address: 0x1300
  # address: 0x1200
  # offset: 0x0100
  address: 0x1300
  offset: 0x0000
  register_type: holding
  value_type: U_DWORD
  register_count: 0x0E  # read up to PCLModuleSta 0x010C
  response_size: 0x1C
# device_class: timestamp
  state_class: measurement
  unit_of_measurement: "s"
  accuracy_decimals: 0
  id: RTCTicks

  #         0x0108  264 UINT32  4   R   Sleep time                                          TimeEnterSleep      S
- platform: modbus_controller
  modbus_controller_id: ${modbus_contr_id}
  name: "${name} Sleep time"
  # address: 0x1308
  # address: 0x1200
  # offset: 0x0108
  address: 0x1300
  offset: 0x0008
  register_type: holding
  value_type: U_DWORD
# device_class: timestamp
  state_class: measurement
  unit_of_measurement: "s"
  accuracy_decimals: 0
  id: TimeEnterSleep

  #         0x010C  268 UINT8   2   R   Parallel current limiting module status             PCLModuleSta            1: open; 0: close
  #                     UINT8           Reserved RVD
- platform: modbus_controller
  modbus_controller_id: ${modbus_contr_id}
  name: "${name} Parallel current limiting module status"     # 
  # address: 0x130C
  # address: 0x1200
  # offset: 0x010C
  address: 0x1300
  offset: 0x000C
  bitmask: 0xFF00
  register_type: holding
  value_type: U_WORD

# - platform: modbus_controller
#   modbus_controller_id: ${modbus_contr_id}
#   name: "${name} Charger status"    # ChargerPlugged
#   # address: 0x130C
#   address: 0x1200
#   offset: 0x010C
#   register_type: holding
#   value_type: U_WORD
#   bitmask: 0x00FF
