#     # *  0x006C  108 UINT32  4   RW  CellCount                                           CellCount           string                     number
# - platform: modbus_controller
#   modbus_controller_id: ${modbus_contr_id}
#   # name: "${name} CellCount"
#   id: CellCountS
#   # address: 0x106C
#   address: 0x1000
#   offset: 0x006C
#   register_type: holding
#   value_type: U_DWORD
#   # skip_updates: 1

    # *  0x0070  112 UINT32  4   RW  Charging switch                                     BatChargeEN             1: open; 0: close      switch
- platform: modbus_controller
  modbus_controller_id: ${modbus_contr_id}
  # name: "${name} Charging switch"
  id: BatChargeENS
  address: 0x1070
  # address: 0x1070
  # offset: 0x0000
  # register_count: 0x06  # 
  # response_size: 0x0C
  register_type: holding
  value_type: U_DWORD
  # skip_updates: 1

    # *  0x0074  116 UINT32  4   RW  Discharge switch                                    BatDisChargeEN          1: open; 0: close      switch
- platform: modbus_controller
  modbus_controller_id: ${modbus_contr_id}
  # name: "${name} Discharge switch"
  id: BatDisChargeENS
  address: 0x1074
  # address: 0x1070
  # offset: 0x0004
  register_type: holding
  value_type: U_DWORD
  # skip_updates: 1

    # *  0x0078  120 UINT32  4   RW  Balance switch                                      BalanEN                 1: open; 0: close      switch
- platform: modbus_controller
  modbus_controller_id: ${modbus_contr_id}
  # name: "${name} Balance switch"
  id: BalanENS
  address: 0x1078
  # address: 0x1070
  # offset: 0x0008
  register_type: holding
  value_type: U_DWORD
  # skip_updates: 1


