# 0x1400  
#         0x00B2  178 UINT8   2   RW  Serial port 1 protocol                              UART1MPRTOLNbr
#                     UINT8       RW  CAN protocol                                        CANMPRTOLNbr
#         0x00B4  180 UINT8   16  R   Serial port 1 protocol control                      UART1MPRTOLEnable
#         0x00D4  212 UINT8   2   RW  Serial port 2 protocol                              UART2MPRTOLNbr
#                     UINT8       R   Serial port 2 protocol control                      UART2MPRTOLEnable[0]
#         0x00E4  228 UINT8   2   RW  LCD buzzer trigger source                           LCDBuzzerTrigger
#                     UINT8           Dry node 1 trigger source                           DRY1Trigger
#         0x00E6  230 UINT8   2   RW  Dry node 2 trigger source                           DRY2Trigger
#                     UINT8       R   UART protocol library version                       UARTMPTLVer                
#         0x00E8  232 INT32   4   RW  LCD buzzer trigger value                            LCDBuzzerTriggerVal
#         0x00EC  236 INT32   4   RW  LCD buzzer recovery value                           LCDBuzzerReleaseVal
#         0x00F0  240 INT32   4   RW  Dry node 1 trigger value                            DRY1TriggerVal
#         0x00F4  244 INT32   4   RW  Dry node 1 trigger value                            DRY1ReleaseVal
#         0x00F8  248 INT32   4   RW  Dry node 2 trigger value                            DRY2TriggerVal
#         0x00FC  252 INT32   4   RW  Dry node 2 recovery value                           DRY2ReleaseVal
#         0x0100  256 INT32   4   RW  Data storage period                                 DataStoredPeriod
#         0x0104  260 UINT8   2   RW  Charging time                                       RCVTime             0.1H
#                                     Float charge time                                   RFVTime             0.1H
#         0x0106  262 UINT8   2   R   CAN protocol library version                        CANMPTLVer
#                                     Preserve RVD

# THIS IS FOR TEST ONLY - not required in normal operation - to check value of all 16 registers
# Returned string: [D][text_sensor:064]: 'jk-bms0 Serial port 1 protocol control string': Sending state 'ff670000000000000000000000000000'
#                  [D][uart_debug:114]: <<< 01:03:10:FF:67:00:00:00:00:00:00:00:00:00:00:00:00:00:00:C2:C3

#         0x00B4  180 UINT8   16  R   Serial port 1 protocol control                      UART1MPRTOLEnable
- platform: modbus_controller
  modbus_controller_id: ${modbus_contr_id}
  name: "${name} Serial port 1 protocol control string"   # UART1MPRTOLEnable
  id: UART1MPRTOLEnableS
  address: 0x14B4
  # address: 0x14B4       
  # offset: 0x0000
  # register_count: 0x0A   
  # response_size: 0x14
  register_count: 0x08   
  response_size: 0x10
  # bitmask: 0xFF00
  register_type: holding
  raw_encode: HEXBYTES

